version: 2

project_name: rollbaz

before:
  hooks:
    - go mod tidy

builds:
  - id: rollbaz
    main: ./cmd/rollbaz
    binary: rollbaz
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: github

release:
  github:
    owner: kevinsheth
    name: rollbaz
